
//@file  javascript interface dispatcher generated by intergen v6
//See LICENSE file for copyright and license information

#include <comm/metastream/metastream.h>
#include <comm/metastream/fmtstream_v8.h>
#include <comm/binstream/filestream.h>
#include <comm/binstream/binstreambuf.h>

#include "ifc/plugin_interface.js.h"

using namespace coid;

#ifdef V8_MAJOR_VERSION

#define UNDEFINED           v8::Local<v8::Value>()
#define NULLv8(iso)         v8::Null(iso)

#define HANDLE_SCOPE(iso,hs)    v8::HandleScope hs(iso)
#define ESCAPABLE_SCOPE(iso,hs) v8::EscapableHandleScope hs(iso)
#define ESCAPE(hs,h)        hs.Escape(h)

#define ARGUMENTS           v8::FunctionCallbackInfo<v8::Value>
#define CBK_RET             void
#define CBK_UNDEFINED

#define NEWTYPE(iso,t)      v8::t::New(iso)
#define NEWTYPE2(iso,t,a)   v8::t::New(iso, a)
#define PERSISTENT(iso,o,n) o.Reset(iso, n)
#define RESET(o)            o.Reset()
#define LOCAL(iso,o)        o.Get(iso)
#define CUR_CONTEXT(iso)    iso->GetCurrentContext()

#else

#define UNDEFINED           v8::Undefined()
#define NULLv8(iso)         v8::Null()

#define HANDLE_SCOPE(iso,hs)    v8::HandleScope hs
#define ESCAPABLE_SCOPE(iso,hs) v8::HandleScope hs
#define ESCAPE(hs,h)        hs.Close(h)

#define ARGUMENTS           v8::Arguments
#define CBK_RET             v8::Handle<v8::Value>
#define CBK_UNDEFINED       v8::Undefined()

#define NEWTYPE(iso,t)      v8::t::New()
#define NEWTYPE2(iso,t,a)   v8::t::New(a)
#define PERSISTENT(iso,o,n) o = o.New(iso,n)
#define RESET(o)            do { if (!o.IsWeak()) o.Dispose(); o.Clear(); } while(0)
#define LOCAL(iso,o)        o
#define CUR_CONTEXT(iso)    v8::Context::GetCurrent()

#endif

////////////////////////////////////////////////////////////////////////////////
//
// javascript handler of interface plugin_interface of class plugin
//
////////////////////////////////////////////////////////////////////////////////

namespace js {

////////////////////////////////////////////////////////////////////////////////
///Interface declaration: [namespace::]name, path
class plugin_interface_js_dispatcher
    : public ::js::interface_wrapper_base<::plugin_interface>
{
#ifdef V8_MAJOR_VERSION
    static void _js_release_callback(const v8::WeakCallbackInfo<void*>& data)
    {
        void* p = data.GetParameter();
        plugin_interface_js_dispatcher* ifc = static_cast<plugin_interface_js_dispatcher*>(p);
        ifc->_object.Empty();
        ifc->release_refcount();
    }

#else

    static void _js_release_callback(v8::Persistent<v8::Value> object, void* p)
    {
        plugin_interface_js_dispatcher* ifc = static_cast<plugin_interface_js_dispatcher*>(p);
        DASSERT( ifc->_object == object );
        ifc->_object.Clear();
        ifc->release_refcount();

        object.Dispose();
    }
#endif

protected:

    EBackend intergen_backend() const override { return IFC_BACKEND_JS; }

public:

    v8::Handle<v8::Object> create_interface_object( bool make_weak );

    static v8::Handle<v8::Script> load_script( const coid::token& scriptfile, const coid::token& file_name );

    COIDNEWDELETE("plugin_interface_js_dispatcher");

    plugin_interface_js_dispatcher()
    {}

    plugin_interface_js_dispatcher( plugin_interface* orig ) {
        _base.create(orig);
        _vtable = _base->vtable();
        //PERSISTENT(v8::Isolate::GetCurrent(), _context, context);

		_host = _base->host<policy_intrusive_base>();
    }

    ~plugin_interface_js_dispatcher() {
        RESET(_object);

        //RESET(_script);
        //RESET(_context);
    }

    bool intergen_bind_capture( coid::binstring* capture, uint instid ) override
    {
        return _real()->intergen_bind_capture(capture, instid);
    }

    void intergen_capture_dispatch( uint mid, coid::binstring& bin ) override
    {
        _real()->intergen_capture_dispatch(mid, bin);
    }

    // --- creators ---

    ///Interface creator
    static iref<plugin_interface_js_dispatcher> get( const script_handle& scriptpath, const coid::token& bindname, v8::Handle<v8::Context>* );

    static v8::Handle<v8::Value> v8creator_get0(const ARGUMENTS& args, interface_context* ifc);

    ///Handler for generic $query_interface javascript method
    static CBK_RET v8query_interface( const ARGUMENTS& args );
    static CBK_RET v8query_interface_global( const ARGUMENTS& args );
    static CBK_RET v8log( const ARGUMENTS& args );
    static CBK_RET v8rebind_events( const ARGUMENTS& args );
    static CBK_RET v8current_global( const ARGUMENTS& args );

    // --- method wrappers ---

    static CBK_RET v8_set_value0( const ARGUMENTS& args );
    static CBK_RET v8_get_value1( const ARGUMENTS& args );
};

////////////////////////////////////////////////////////////////////////////////
CBK_RET plugin_interface_js_dispatcher::v8_set_value0( const ARGUMENTS& args )
{
    v8::Isolate* iso = args.GetIsolate();

    if (args.Length() < 1 || args.Length() > 1) { //in/inout arguments
        coid::charstr tmp = "Wrong number of arguments in ";
        tmp << "plugin_interface.set_value";
        return (CBK_RET)::js::THROW(iso, v8::Exception::SyntaxError, tmp);
    }

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::Local<v8::Object> obj__ = args.Holder();
    if (obj__.IsEmpty() || obj__->InternalFieldCount() == 0)
        return CBK_UNDEFINED;

    v8::Local<v8::Value> intobj__ = obj__->GetInternalField(0);
    if (!intobj__->IsExternal())
        return CBK_UNDEFINED;

    ::js::interface_wrapper_base<::plugin_interface>* ifc = static_cast<::js::interface_wrapper_base<::plugin_interface>*>
        (v8::Handle<v8::External>::Cast(intobj__)->Value());

    auto R_ = ifc ? ifc->_real() : 0;
    if (!R_) {
        coid::charstr tmp = "Null interface object in ";
        tmp << "plugin_interface.set_value";
        return (CBK_RET)::js::THROW(iso, &v8::Exception::ReferenceError, tmp);
    }

    v8::Context::Scope context_scope(ifc->context(iso));

    try {
    THREAD_SINGLETON(v8_streamer_context).reset();

    //stream the arguments in
    static_assert(CHECK::meta_operator_exists<int>::value, "missing metastream operator 'int'");

    threadcached<int> x;
    from_v8(args[0], x);

    //invoke
    R_->set_value(x);

    //stream out
    v8::Handle<v8::Object> r__;

#ifdef V8_MAJOR_VERSION
    args.GetReturnValue().Set(r__);
#else
    return ESCAPE(handle_scope__, r__);
#endif

    } catch(const coid::exception& e) {
        return (CBK_RET)::js::THROW(iso, &v8::Exception::TypeError, e.text());
    }
}

////////////////////////////////////////////////////////////////////////////////
CBK_RET plugin_interface_js_dispatcher::v8_get_value1( const ARGUMENTS& args )
{
    v8::Isolate* iso = args.GetIsolate();

    if (args.Length() < 0 || args.Length() > 0) { //in/inout arguments
        coid::charstr tmp = "Wrong number of arguments in ";
        tmp << "plugin_interface.get_value";
        return (CBK_RET)::js::THROW(iso, v8::Exception::SyntaxError, tmp);
    }

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::Local<v8::Object> obj__ = args.Holder();
    if (obj__.IsEmpty() || obj__->InternalFieldCount() == 0)
        return CBK_UNDEFINED;

    v8::Local<v8::Value> intobj__ = obj__->GetInternalField(0);
    if (!intobj__->IsExternal())
        return CBK_UNDEFINED;

    ::js::interface_wrapper_base<::plugin_interface>* ifc = static_cast<::js::interface_wrapper_base<::plugin_interface>*>
        (v8::Handle<v8::External>::Cast(intobj__)->Value());

    auto R_ = ifc ? ifc->_real() : 0;
    if (!R_) {
        coid::charstr tmp = "Null interface object in ";
        tmp << "plugin_interface.get_value";
        return (CBK_RET)::js::THROW(iso, &v8::Exception::ReferenceError, tmp);
    }

    v8::Context::Scope context_scope(ifc->context(iso));

    try {
    THREAD_SINGLETON(v8_streamer_context).reset();

    //stream the arguments in

    //invoke
    int _rval_ = R_->get_value();

    //stream out
    v8::Handle<v8::Value> r__;
    static_assert( CHECK::meta_operator_exists<int>::value, "missing metastream operator for 'int'" );
    r__ = to_v8(_rval_);

#ifdef V8_MAJOR_VERSION
    args.GetReturnValue().Set(r__);
#else
    return ESCAPE(handle_scope__, r__);
#endif

    } catch(const coid::exception& e) {
        return (CBK_RET)::js::THROW(iso, &v8::Exception::TypeError, e.text());
    }
}


////////////////////////////////////////////////////////////////////////////////
CBK_RET plugin_interface_js_dispatcher::v8log( const ARGUMENTS& args )
{
    v8::Isolate* iso = args.GetIsolate();

    if (args.Length() == 0)
        return CBK_UNDEFINED;

    const void* inst = 0;

    v8::Local<v8::Object> obj__ = args.Holder();
    if (!obj__.IsEmpty() && obj__->InternalFieldCount() > 0) {
        v8::Local<v8::Value> intobj__ = obj__->GetInternalField(0);
        if (intobj__->IsExternal()) {
            js::plugin_interface_js_dispatcher* ifc = static_cast<js::plugin_interface_js_dispatcher*>
                (v8::Handle<v8::External>::Cast(intobj__)->Value());

            inst = ifc;
            if (!ifc)
                return (CBK_RET)::js::THROW(iso, &v8::Exception::ReferenceError, "Null interface object in $log");
        }
    }

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::String::Utf8Value key(args[0]);

    coid::token tokey(*key, key.length());

    intergen_interface::ifclog_ext(coid::ELogType::None, coid::tokenhash("plugin_interface"),
        inst, tokey);

    return CBK_UNDEFINED;
}

////////////////////////////////////////////////////////////////////////////////
CBK_RET plugin_interface_js_dispatcher::v8query_interface( const ARGUMENTS& args )
{
    v8::Isolate* iso = args.GetIsolate();

    if (args.Length() < 1)
        return (CBK_RET)::js::THROW(iso, &v8::Exception::Error, "Interface creator name missing");

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::String::Utf8Value key(args[0]);

    typedef v8::Handle<v8::Value> (*fn_get)(const ARGUMENTS&, interface_context*);
    coid::token tokey(*key, key.length());
    fn_get get = reinterpret_cast<fn_get>(
        coid::interface_register::get_interface_creator(tokey));

    if (!get) {
        coid::charstr tmp = "interface creator ";
        tmp << tokey << " not found";
        return (CBK_RET)::js::THROW(iso, v8::Exception::Error, tmp);
    }

    v8::Local<v8::Object> obj__ = args.Holder();
    if (obj__.IsEmpty() || obj__->InternalFieldCount() == 0)
        return CBK_UNDEFINED;

    v8::Local<v8::Value> intobj__ = obj__->GetInternalField(0);
    if (!intobj__->IsExternal())
        return CBK_UNDEFINED;

    js::plugin_interface_js_dispatcher* ifc = static_cast<js::plugin_interface_js_dispatcher*>
        (v8::Handle<v8::External>::Cast(intobj__)->Value());

    if (!ifc)
        return (CBK_RET)::js::THROW(iso, &v8::Exception::ReferenceError, "Null interface object in $query_interface");

#ifdef V8_MAJOR_VERSION
    args.GetReturnValue().Set(get(args, ifc));
#else
    return ESCAPE(handle_scope__, get(args, ifc));
#endif
}

////////////////////////////////////////////////////////////////////////////////
CBK_RET plugin_interface_js_dispatcher::v8query_interface_global( const ARGUMENTS& args )
{
    v8::Isolate* iso = args.GetIsolate();

    if (args.Length() < 1)
        return (CBK_RET)::js::THROW(iso, &v8::Exception::Error, "Interface creator name missing");

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::String::Utf8Value key(args[0]);

    typedef v8::Handle<v8::Value> (*fn_get)(const ARGUMENTS&, interface_context*);
    coid::token tokey(*key, key.length());
    fn_get get = reinterpret_cast<fn_get>(
        coid::interface_register::get_interface_creator(tokey));

    if (!get) {
        coid::charstr tmp = "interface creator ";
        tmp << tokey << " not found";
        return (CBK_RET)::js::THROW(iso, v8::Exception::Error, tmp);
    }

#ifdef V8_MAJOR_VERSION
    args.GetReturnValue().Set(get(args, 0));
#else
    return ESCAPE(handle_scope__, get(args, 0));
#endif
}

////////////////////////////////////////////////////////////////////////////////
CBK_RET plugin_interface_js_dispatcher::v8rebind_events( const ARGUMENTS& args )
{
    return CBK_UNDEFINED;
}

////////////////////////////////////////////////////////////////////////////////
CBK_RET plugin_interface_js_dispatcher::v8current_global( const ARGUMENTS& args )
{
    v8::Isolate* iso = args.GetIsolate();

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::Local<v8::Object> obj__ = args.Holder();
    if (obj__.IsEmpty() || obj__->InternalFieldCount() == 0)
        return CBK_UNDEFINED;

    v8::Local<v8::Value> intobj__ = obj__->GetInternalField(0);
    if (!intobj__->IsExternal())
        return CBK_UNDEFINED;

    js::plugin_interface_js_dispatcher* ifc = static_cast<js::plugin_interface_js_dispatcher*>
        (v8::Handle<v8::External>::Cast(intobj__)->Value());

#ifdef V8_MAJOR_VERSION
    args.GetReturnValue().Set(ifc->context(iso)->Global()->GetPrototype());
#else
    return ESCAPE(handle_scope__, ifc->context(iso)->Global()->GetPrototype());
#endif
}

////////////////////////////////////////////////////////////////////////////////
v8::Handle<v8::Object> plugin_interface_js_dispatcher::create_interface_object( bool make_weak )
{
    v8::Isolate* iso = v8::Isolate::GetCurrent();

    static v8::Persistent<v8::ObjectTemplate> _objtempl;
    if (_objtempl.IsEmpty())
    {
        v8::Local<v8::ObjectTemplate> ot = NEWTYPE(iso, ObjectTemplate);
        ot->SetInternalFieldCount(2);    //ptr and class hash id

        ot->Set(v8::symbol("set_value"), NEWTYPE2(iso, FunctionTemplate, &v8_set_value0));
        ot->Set(v8::symbol("get_value"), NEWTYPE2(iso, FunctionTemplate, &v8_get_value1));

        ot->Set(v8::symbol("$query_interface"), NEWTYPE2(iso, FunctionTemplate, &v8query_interface));
        ot->Set(v8::symbol("$rebind_events"), NEWTYPE2(iso, FunctionTemplate, &v8rebind_events));
        ot->Set(v8::symbol("$ctx"), NEWTYPE2(iso, FunctionTemplate, &v8current_global));
        ot->Set(v8::symbol("$log"), NEWTYPE2(iso, FunctionTemplate, &v8log));

        PERSISTENT(iso, _objtempl, ot);
    }

    v8::Local<v8::Object> obj = LOCAL(iso, _objtempl)->NewInstance();

    v8::Handle<v8::External> map_ptr = NEWTYPE2(iso, External, this);
    obj->SetInternalField(0, map_ptr);
    v8::Handle<v8::External> hash_ptr = NEWTYPE2(iso, External, (void*)ints(1320019967));
    obj->SetInternalField(1, hash_ptr);

    if (make_weak) {
        PERSISTENT(iso, _object, obj);

#ifdef V8_MAJOR_VERSION
        void* p = this;
        _object.SetWeak(&p, _js_release_callback, v8::WeakCallbackType::kParameter);
        //_context.SetWeak();
#else
        _object.MakeWeak(this, _js_release_callback);
        //_context.MakeWeak(0, _js_release_callback);
#endif
        add_refcount();
    }

    return obj;
}

////////////////////////////////////////////////////////////////////////////////
v8::Handle<v8::Script> plugin_interface_js_dispatcher::load_script( const coid::token& script, const coid::token& fname )
{
    v8::Local<v8::String> scriptv8 = v8::string_utf8(script);

    // set up an error handler to catch any exceptions the script might throw.
    v8::TryCatch trycatch__;

    v8::Handle<v8::Script> compiled_script = v8::Script::Compile(scriptv8, v8::string_utf8(fname));
    if (trycatch__.HasCaught())
        script_handle::throw_js_error(trycatch__, "js::plugin_interface::load_script(): ");

    compiled_script->Run();
    if (trycatch__.HasCaught())
        script_handle::throw_js_error(trycatch__, "js::plugin_interface::load_script(): ");

    return compiled_script;
}

// --- creators ---

////////////////////////////////////////////////////////////////////////////////
iref<plugin_interface_js_dispatcher> plugin_interface_js_dispatcher::get( const script_handle& script, const coid::token& bindname, v8::Handle<v8::Context>* ctx )
{
    v8::Isolate* iso = v8::Isolate::GetCurrent();

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::Handle<v8::Context> context;

    // create interface object
    iref<plugin_interface_js_dispatcher> ifc = plugin_interface::get(new plugin_interface_js_dispatcher);
    if (!ifc)
        throw coid::exception() << "failed to create interface object";

    // check if an external context provider is required
    if (script.is_path()) {
        coid::token path = script.str();
        path.cut_right('?', coid::token::cut_trait_remove_sep_default_empty());

        bool ispage = path.begins_with("http://") || path.begins_with("https://") || path.ends_with(".html");
        bool isscript = path.ends_with(".js");

        if (ispage && !isscript) {
            typedef v8::Handle<v8::Context> (*fn_getctx)(const coid::token&, policy_intrusive_base*);

            fn_getctx ctxgetter = reinterpret_cast<fn_getctx>(
                    coid::interface_register::get_interface_creator("~html@system_context_getter2"));

            if (!ctxgetter)
                throw coid::exception() << "unable to acquire the system context creator interface";

            context = ctxgetter(script.str(), ifc.get());
        }
    }

    bool extctx = !context.IsEmpty();

    if (!extctx) {
        if (script.has_context())
            context = script.context();
        else
            context = NEWTYPE(iso, Context);
    }

    if (ctx)
        *ctx = ESCAPE(handle_scope__, context);

    v8::Context::Scope context_scope(context);
    //PERSISTENT(iso, ifc->_context, context);

    if (!extctx && !script.is_context())
    {
        if (!script.has_context()) {
            context->Global()->Set(v8::string_utf8("$include"), NEWTYPE2(iso, FunctionTemplate, &script_handle::js_include)->GetFunction());
            context->Global()->Set(v8::string_utf8("$query_interface"), NEWTYPE2(iso, FunctionTemplate, &plugin_interface_js_dispatcher::v8query_interface_global)->GetFunction());
            context->Global()->Set(v8::string_utf8("$log"), NEWTYPE2(iso, FunctionTemplate, &plugin_interface_js_dispatcher::v8log)->GetFunction());
        }

        coid::token script_tok;
        coid::charstr script_tmp;
        if (script.is_path()) {
            coid::bifstream bif (script.str());
            if (!bif.is_open())
                throw coid::exception() << script.str() << " not found";

            script_tmp = script.prefix();

            coid::binstreambuf buf;
            buf.swap(script_tmp);
            buf.transfer_from(bif);
            buf.swap(script_tmp);

            script_tok = script_tmp;
        }
        else if (script.prefix()) {
            script_tmp << script.prefix() << script.str();
            script_tok = script_tmp;
        }
        else {
            script_tok = script.str();
        }

        PERSISTENT(iso, ifc->_object, ifc->create_interface_object(false));
        if (bindname)
            context->Global()->Set(v8::string_utf8(bindname), LOCAL(iso, ifc->_object));

        v8::Handle<v8::Script> compiled_script = load_script(script_tok, script.url());

        //PERSISTENT(iso, ifc->_script, compiled_script);
    }
    else {
        PERSISTENT(iso, ifc->_object, ifc->create_interface_object(false));

        if (bindname)
            context->Global()->Set(v8::string_utf8(bindname), LOCAL(iso, ifc->_object));
    }

    return ifc;
}

////////////////////////////////////////////////////////////////////////////////
///Creator methods for access from JS
v8::Handle<v8::Value> plugin_interface_js_dispatcher::v8creator_get0( const ARGUMENTS& args, interface_context* ifc )
{
    v8::Isolate* iso = args.GetIsolate();

    if (args.Length() < 1+0 || args.Length() > 1+0) { //fnc name + in/inout arguments
        coid::charstr tmp = "Wrong number of arguments in ";
        tmp << "get";
        ::js::THROW(iso, &v8::Exception::Error, tmp);
        return UNDEFINED;
    }

    ESCAPABLE_SCOPE(iso, handle_scope__);
    v8::Local<v8::Object> obj__ = args.Holder();

    //js::plugin_interface_js_dispatcher* ifc = static_cast<js::plugin_interface_js_dispatcher*>
    //    (v8::Handle<v8::External>::Cast(obj__->GetInternalField(0))->Value());

    v8::Local<v8::Context> ctx = ifc && !ifc->_object.IsEmpty()
        ? ifc->context(iso)
        : CUR_CONTEXT(iso);
    v8::Context::Scope context_scope(ctx);

    //stream the arguments in
    THREAD_SINGLETON(v8_streamer_context).reset();

    //invoke
    iref<plugin_interface_js_dispatcher> nifc = plugin_interface::get(new plugin_interface_js_dispatcher);
    //if (nifc)
    //    PERSISTENT(iso, nifc->_context, ctx);//ifc->_context);

    //stream out
    v8::Handle<v8::Value> r__ = nifc ? v8::Handle<v8::Value>(nifc->create_interface_object(true)) : NULLv8(iso);
    
    return ESCAPE(handle_scope__, r__);
}

////////////////////////////////////////////////////////////////////////////////
///Create JS wrapper from an existing interface object
v8::Handle<v8::Value> create_wrapper_plugin_interface( ::plugin_interface* orig, v8::Handle<v8::Context> context )
{
    v8::Isolate* iso = v8::Isolate::GetCurrent();

    // check that the orig points to an object
    if (!orig) return NULLv8(iso);

    if (context.IsEmpty()) {
        context = CUR_CONTEXT(iso);
    }

    v8::Context::Scope context_scope(context);
    ESCAPABLE_SCOPE(iso, scope);

    iref<js::plugin_interface_js_dispatcher> ifc;
    v8::Handle<v8::Object> obj;

    if (orig->intergen_backend() == intergen_interface::IFC_BACKEND_JS)
        obj = LOCAL(iso, static_cast<plugin_interface_js_dispatcher*>(orig)->_object);

    if (obj.IsEmpty()) {
        // create interface object
        ifc.create(new js::plugin_interface_js_dispatcher(static_cast<::plugin_interface*>(orig)));

        obj = ifc->create_interface_object(true);
    }

    return ESCAPE(scope, obj);
}

////////////////////////////////////////////////////////////////////////////////
static void register_binders_for_plugin_interface( bool on )
{
    interface_register::register_interface_creator(
        "plugin_interface.get@creator.js",
        on ? (void*)&plugin_interface_js_dispatcher::get : nullptr);
    interface_register::register_interface_creator(
        "js::plugin_interface.get",
        on ? (void*)&plugin_interface_js_dispatcher::v8creator_get0 : nullptr);
    interface_register::register_interface_creator(
        "plugin_interface@wrapper.js",
        on ? (void*)&create_wrapper_plugin_interface : nullptr);

}

//auto-register the bind function
LOCAL_SINGLETON_DEF(ifc_autoregger) plugin_interface_autoregger = new ifc_autoregger(&register_binders_for_plugin_interface);


void* force_register_plugin_interface() {
    LOCAL_SINGLETON_DEF(ifc_autoregger) autoregger = new ifc_autoregger(&register_binders_for_plugin_interface);
    return autoregger.get();
}

} //namespace js

